#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_DIR=""  # resolved interactively after helper functions are loaded

SUDO=""
if [[ "${EUID}" -ne 0 ]]; then
  SUDO="sudo"
fi

# ── Install mode ──────────────────────────────────────────────────────────────
# --dev  Hot-reload dev install (localhost only, volume-mounted source, Vite HMR).
#        Code changes in backend/ and frontend/src/ take effect without reinstalling.
INSTALL_MODE="prod"
for arg in "$@"; do
  if [[ "$arg" == "--dev" ]]; then
    INSTALL_MODE="dev"
  fi
done

log() { printf "\n[%s] %s\n" "$(date +'%H:%M:%S')" "$*"; }
die() { echo "ERROR: $*" >&2; exit 1; }
warn() { echo "WARN: $*" >&2; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

run_with_retry() {
  local attempts="$1"
  local delay="$2"
  shift 2
  local n=1
  while true; do
    if "$@"; then
      return 0
    fi
    if [[ "$n" -ge "$attempts" ]]; then
      return 1
    fi
    warn "Command failed (attempt $n/$attempts): $*"
    sleep "$delay"
    n=$((n + 1))
  done
}

is_valid_email() {
  [[ "$1" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]]
}

is_valid_domain() {
  local d="$1"
  if [[ "$d" == "localhost" ]]; then
    return 0
  fi
  [[ "$d" =~ ^[A-Za-z0-9.-]+$ ]] && [[ "$d" == *.* ]]
}

is_valid_port() {
  local p="$1"
  [[ "$p" =~ ^[0-9]+$ ]] && (( p >= 1 && p <= 65535 ))
}

port_in_use() {
  local port="$1"
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi
  if command -v ss >/dev/null 2>&1; then
    ss -ltn "( sport = :$port )" | grep -q ":$port"
    return $?
  fi
  return 1
}

next_free_port() {
  local start="$1"
  local p="$start"
  while port_in_use "$p"; do
    p=$((p + 1))
    if [[ "$p" -gt 65535 ]]; then
      die "No free port found starting from $start"
    fi
  done
  echo "$p"
}

prompt_required() {
  local var_name="$1"
  local prompt_text="$2"
  local value=""
  while [[ -z "$value" ]]; do
    read -r -p "$prompt_text: " value
    value="$(echo "$value" | sed 's/^ *//;s/ *$//')"
  done
  printf -v "$var_name" "%s" "$value"
}

prompt_with_default() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  local value=""
  read -r -p "$prompt_text [$default_value]: " value
  value="$(echo "$value" | sed 's/^ *//;s/ *$//')"
  if [[ -z "$value" ]]; then
    value="$default_value"
  fi
  printf -v "$var_name" "%s" "$value"
}

resolve_root_dir() {
  local default_dir="${HOME}/.knotwork"
  prompt_with_default ROOT_DIR "Installation directory" "$default_dir"
  # expand leading tilde
  ROOT_DIR="${ROOT_DIR/#\~/$HOME}"
  mkdir -p "$ROOT_DIR"
  cd "$ROOT_DIR"
}

set_env_key() {
  local key="$1"
  local value="$2"
  local file="$3"
  local esc="$value"
  esc="${esc//\\/\\\\}"
  esc="${esc//&/\\&}"
  if grep -q "^${key}=" "$file"; then
    sed -i.bak "s#^${key}=.*#${key}=${esc}#g" "$file"
  else
    printf "%s=%s\n" "$key" "$value" >> "$file"
  fi
}

write_env_file() {
  local path="$1"
  cat > "$path" <<EOF
# Generated by scripts/install.sh
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
KNOTWORK_NETWORK_NAME=${KNOTWORK_NETWORK_NAME}
DATABASE_URL=postgresql+asyncpg://knotwork:knotwork@postgres:5432/knotwork
DATABASE_URL_SYNC=postgresql://knotwork:knotwork@postgres:5432/knotwork
REDIS_URL=redis://redis:6379
STORAGE_ADAPTER=${STORAGE_ADAPTER}
LOCAL_FS_ROOT=${LOCAL_FS_ROOT}
OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
DEFAULT_MODEL=${DEFAULT_MODEL}
JWT_SECRET=${JWT_SECRET}
AUTH_DEV_BYPASS_USER_ID=${AUTH_DEV_BYPASS_USER_ID}
FRONTEND_URL=${FRONTEND_URL}
BACKEND_URL=${BACKEND_URL}
OPENCLAW_PLUGIN_PACKAGE_URL=${OPENCLAW_PLUGIN_PACKAGE_URL}
RESEND_API=${RESEND_API}
EMAIL_FROM=${EMAIL_FROM}
BACKEND_HOST_PORT=${BACKEND_HOST_PORT}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}
BACKEND_DEV_HOST_PORT=${BACKEND_DEV_HOST_PORT}
FRONTEND_DEV_HOST_PORT=${FRONTEND_DEV_HOST_PORT}
VITE_API_URL=${VITE_API_URL}
EOF
}

write_install_manifest() {
  local path="$1"
  cat > "$path" <<EOF
{
  "install_mode": "$( [[ "$DOMAIN" == "localhost" ]] && echo localhost || echo public )",
  "compose_project_name": "${COMPOSE_PROJECT_NAME}",
  "network_name": "${KNOTWORK_NETWORK_NAME}",
  "frontend_url": "${FRONTEND_URL}",
  "backend_url": "${BACKEND_URL}",
  "frontend_host_port": "${FRONTEND_HOST_PORT}",
  "backend_host_port": "${BACKEND_HOST_PORT}",
  "images": [
    "${COMPOSE_PROJECT_NAME}-backend:latest",
    "${COMPOSE_PROJECT_NAME}-worker:latest",
    "${COMPOSE_PROJECT_NAME}-frontend-prod:latest",
    "${COMPOSE_PROJECT_NAME}-backend-dev:latest",
    "${COMPOSE_PROJECT_NAME}-worker-dev:latest",
    "${COMPOSE_PROJECT_NAME}-frontend-dev:latest"
  ]
}
EOF
}

verify_env_postconditions() {
  local expected_owner_id="$1"
  local bypass_value=""
  bypass_value="$(awk -F= '$1=="AUTH_DEV_BYPASS_USER_ID"{print substr($0, index($0,$2)); exit}' .env)"
  [[ "$bypass_value" == "$expected_owner_id" ]] || die "Installer failed to persist AUTH_DEV_BYPASS_USER_ID=${expected_owner_id}"
}

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 -c 'import secrets; print(secrets.token_hex(32))'
  fi
}

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g'
}

require_non_local_host_software() {
  command -v nginx >/dev/null 2>&1 \
    || die "Non-local installs require host nginx. Install nginx first, then rerun the installer."
  command -v certbot >/dev/null 2>&1 \
    || die "Non-local installs require certbot for Let's Encrypt. Install certbot first, then rerun the installer."
}

ensure_nginx_port_available() {
  if port_in_use 80; then
    if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet nginx; then
      return
    fi
    die "Host port 80 is already in use by another process. Free it before installer runs nginx."
  fi
  if port_in_use 443; then
    if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet nginx; then
      return
    fi
    die "Host port 443 is already in use by another process. Free it before installer runs nginx TLS."
  fi
}

restart_nginx_service() {
  if command -v systemctl >/dev/null 2>&1; then
    $SUDO systemctl enable nginx || true
    $SUDO systemctl restart nginx
    return
  fi
  if command -v service >/dev/null 2>&1; then
    $SUDO service nginx restart
    return
  fi
  die "No service manager found to restart nginx."
}

resolve_server_ip() {
  local ip
  ip="$(curl -4 -s --max-time 3 ifconfig.me || true)"
  if [[ -z "$ip" ]]; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  echo "$ip"
}

resolve_domain_ipv4() {
  local domain="$1"
  if command -v getent >/dev/null 2>&1; then
    getent ahostsv4 "$domain" 2>/dev/null | awk '{print $1}' | sort -u | tr '\n' ' '
    return
  fi
  if command -v dig >/dev/null 2>&1; then
    dig +short A "$domain" 2>/dev/null | sort -u | tr '\n' ' '
    return
  fi
  if command -v nslookup >/dev/null 2>&1; then
    nslookup "$domain" 2>/dev/null | awk '/^Address: /{print $2}' | sort -u | tr '\n' ' '
    return
  fi
  echo ""
}

wait_for_dns() {
  local domain="$1"
  local server_ip="$2"
  log "Checking DNS for $domain (expected server IP: ${server_ip:-unknown})"
  while true; do
    local resolved
    resolved="$(resolve_domain_ipv4 "$domain")"
    echo "Resolved IPv4: ${resolved:-<none>}"
    if [[ -n "$server_ip" && "$resolved" == *"$server_ip"* ]]; then
      echo "DNS looks correct."
      break
    fi
    read -r -p "DNS not ready. Press Enter to re-check or type 'skip' to continue: " ans
    if [[ "$ans" == "skip" ]]; then
      break
    fi
  done
}

write_nginx_config() {
  local domain="$1"
  local backend_port="$2"
  local frontend_port="$3"
  local conf_path="/etc/nginx/sites-available/knotwork.conf"
  log "Writing nginx config: $conf_path"
  $SUDO tee "$conf_path" >/dev/null <<EOF
server {
    listen 80;
    server_name ${domain};

    client_max_body_size 25M;

    location /api/v1/ws/ {
        proxy_pass http://127.0.0.1:${backend_port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:${backend_port};
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /ws/ {
        proxy_pass http://127.0.0.1:${backend_port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \$host;
    }

    location /agent-api/ {
        proxy_pass http://127.0.0.1:${backend_port};
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /openclaw-plugin/ {
        proxy_pass http://127.0.0.1:${backend_port};
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /health {
        proxy_pass http://127.0.0.1:${backend_port};
        proxy_set_header Host \$host;
    }

    location / {
        proxy_pass http://127.0.0.1:${frontend_port};
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
  $SUDO ln -sf "$conf_path" /etc/nginx/sites-enabled/knotwork.conf
  if [[ -f /etc/nginx/sites-enabled/default ]]; then
    $SUDO rm -f /etc/nginx/sites-enabled/default
  fi
  $SUDO nginx -t
  restart_nginx_service
}

request_tls() {
  local domain="$1"
  local email="$2"
  if $SUDO test -f "/etc/letsencrypt/live/${domain}/fullchain.pem"; then
    log "TLS certificate already exists for ${domain}; skipping certbot request."
    return
  fi
  log "Requesting Let's Encrypt certificate for ${domain}..."
  run_with_retry 2 5 \
    $SUDO certbot --nginx --non-interactive --agree-tos -m "$email" -d "$domain" --redirect \
    || die "Let's Encrypt request failed for ${domain}. Check DNS/ports and retry."
}

wait_backend_health() {
  local backend_port="$1"
  log "Waiting for backend health..."
  for _ in $(seq 1 60); do
    if curl -fsS "http://127.0.0.1:${backend_port}/health" >/dev/null 2>&1; then
      echo "Backend is healthy."
      return
    fi
    sleep 2
  done
  die "Backend did not become healthy in time."
}

resolve_root_dir

require_cmd curl
require_cmd python3
if ! command -v docker >/dev/null 2>&1; then
  die "Docker is required to install Knotwork. Install Docker first, then rerun this script."
fi
if ! docker compose version >/dev/null 2>&1; then
  die "Docker Compose plugin is required (docker compose ...). Install or enable it first."
fi
docker info >/dev/null 2>&1 || die "Docker daemon is not reachable. Start Docker first."
[[ -f "$SCRIPT_DIR/.env.docker.example" ]] || die "Missing .env.docker.example in $SCRIPT_DIR"
[[ -f "$SCRIPT_DIR/docker-compose.yml" ]] || die "Missing docker-compose.yml in $SCRIPT_DIR"

if [[ "$INSTALL_MODE" == "dev" ]]; then
  echo "Knotwork dev installer (localhost only, hot-reload — code changes take effect without reinstalling)"
else
  echo "Knotwork S8.2 installer (single host, host nginx, auto TLS)"
fi

prompt_required OWNER_NAME "Owner full name"
prompt_required OWNER_EMAIL "Owner email"
is_valid_email "$OWNER_EMAIL" || die "Invalid owner email format: $OWNER_EMAIL"

if [[ "$INSTALL_MODE" == "dev" ]]; then
  # Dev installs are always localhost.
  DOMAIN="localhost"
  echo "Domain: localhost (dev mode, hot-reload)"
else
  prompt_with_default DOMAIN "Server domain (use localhost for local install)" "localhost"
  is_valid_domain "$DOMAIN" || die "Invalid domain: $DOMAIN"
  if [[ "$DOMAIN" != "localhost" ]]; then
    require_non_local_host_software
  fi
fi

prompt_with_default STORAGE_ADAPTER "Storage adapter" "local_fs"
prompt_with_default LOCAL_FS_ROOT "Local handbook storage path inside container" "/app/data/knowledge"
prompt_with_default DEFAULT_MODEL "Default model id" "openai/gpt-4o"

prompt_with_default OPENAI_API_KEY "OpenAI API key (leave blank if using Anthropic only)" ""
prompt_with_default ANTHROPIC_API_KEY "Anthropic API key (leave blank if using OpenAI only)" ""
if [[ -z "$OPENAI_API_KEY" && -z "$ANTHROPIC_API_KEY" ]]; then
  die "At least one provider API key is required (OpenAI or Anthropic)."
fi

read -r -p "JWT secret (leave blank to auto-generate): " JWT_SECRET
JWT_SECRET="$(echo "$JWT_SECRET" | sed 's/^ *//;s/ *$//')"
if [[ -z "$JWT_SECRET" ]]; then
  JWT_SECRET="$(gen_secret)"
fi

# ── Port selection ─────────────────────────────────────────────────────────────
DEFAULT_BACKEND_PORT="$(next_free_port 8000)"
DEFAULT_FRONTEND_PORT="$(next_free_port 3000)"
if [[ "$INSTALL_MODE" == "dev" ]]; then
  # Dev mode uses the *-dev docker-compose services which bind BACKEND_DEV_HOST_PORT
  # and FRONTEND_DEV_HOST_PORT.  Prod ports default to same values (unused in dev).
  prompt_with_default BACKEND_DEV_HOST_PORT "Backend dev host port" "$DEFAULT_BACKEND_PORT"
  prompt_with_default FRONTEND_DEV_HOST_PORT "Frontend dev host port" "$DEFAULT_FRONTEND_PORT"
  is_valid_port "$BACKEND_DEV_HOST_PORT" || die "Invalid backend port: $BACKEND_DEV_HOST_PORT"
  is_valid_port "$FRONTEND_DEV_HOST_PORT" || die "Invalid frontend port: $FRONTEND_DEV_HOST_PORT"
  port_in_use "$BACKEND_DEV_HOST_PORT" && die "Backend dev host port ${BACKEND_DEV_HOST_PORT} is already in use."
  port_in_use "$FRONTEND_DEV_HOST_PORT" && die "Frontend dev host port ${FRONTEND_DEV_HOST_PORT} is already in use."
  [[ "$BACKEND_DEV_HOST_PORT" == "$FRONTEND_DEV_HOST_PORT" ]] && die "Backend and frontend host ports cannot be the same."
  BACKEND_HOST_PORT="$BACKEND_DEV_HOST_PORT"
  FRONTEND_HOST_PORT="$FRONTEND_DEV_HOST_PORT"
else
  prompt_with_default BACKEND_HOST_PORT "Backend host port" "$DEFAULT_BACKEND_PORT"
  prompt_with_default FRONTEND_HOST_PORT "Frontend host port" "$DEFAULT_FRONTEND_PORT"
  is_valid_port "$BACKEND_HOST_PORT" || die "Invalid backend port: $BACKEND_HOST_PORT"
  is_valid_port "$FRONTEND_HOST_PORT" || die "Invalid frontend port: $FRONTEND_HOST_PORT"
  port_in_use "$BACKEND_HOST_PORT" && die "Backend host port ${BACKEND_HOST_PORT} is already in use."
  port_in_use "$FRONTEND_HOST_PORT" && die "Frontend host port ${FRONTEND_HOST_PORT} is already in use."
  [[ "$BACKEND_HOST_PORT" == "$FRONTEND_HOST_PORT" ]] && die "Backend and frontend host ports cannot be the same."
  BACKEND_DEV_HOST_PORT="$BACKEND_HOST_PORT"
  FRONTEND_DEV_HOST_PORT="$FRONTEND_HOST_PORT"
fi

if [[ "$DOMAIN" == "localhost" ]]; then
  prompt_with_default FRONTEND_URL "Frontend URL" "http://localhost:${FRONTEND_HOST_PORT}"
  prompt_with_default OPENCLAW_PLUGIN_PACKAGE_URL "OpenClaw plugin package URL (.tar.gz)" "https://lab.crea8r.xyz/kw-plugin/latest"
  prompt_with_default RESEND_API "Resend API key (optional for local)" ""
  prompt_with_default EMAIL_FROM "Email from address (local default)" "noreply@localhost"
  BACKEND_URL="http://localhost:${BACKEND_HOST_PORT}"
  COMPOSE_PROJECT_NAME="knotwork-local"
else
  prompt_with_default FRONTEND_URL "Frontend URL" "https://${DOMAIN}"
  prompt_with_default BACKEND_URL "Backend URL" "https://api.${DOMAIN}"
  prompt_with_default OPENCLAW_PLUGIN_PACKAGE_URL "OpenClaw plugin package URL (.tar.gz)" "https://lab.crea8r.xyz/kw-plugin/latest"
  prompt_required RESEND_API "Resend API key (re_...)"
  prompt_required EMAIL_FROM "From email (verified on Resend)"
  [[ "$FRONTEND_URL" =~ ^https:// ]] || die "FRONTEND_URL must use https:// for non-local domain"
  [[ "$BACKEND_URL" =~ ^https:// ]] || die "BACKEND_URL must use https:// for non-local domain"
  DOMAIN_SLUG="$(slugify "$DOMAIN")"
  COMPOSE_PROJECT_NAME="knotwork-${DOMAIN_SLUG:-prod}"
fi
KNOTWORK_NETWORK_NAME="${COMPOSE_PROJECT_NAME}-network"

if [[ "$DOMAIN" == "localhost" ]]; then
  VITE_API_URL="http://localhost:${BACKEND_HOST_PORT}/api/v1"
else
  VITE_API_URL="${BACKEND_URL%/}/api/v1"
fi

if [[ -f ".env" ]]; then
  cp .env ".env.backup.$(date +%Y%m%d%H%M%S)"
fi
AUTH_DEV_BYPASS_USER_ID=""
write_env_file .env
write_install_manifest .knotwork-install.json

COMPOSE_CMD=(docker compose --project-name "$COMPOSE_PROJECT_NAME" -f "$SCRIPT_DIR/docker-compose.yml")
# Service names and compose profile differ by install mode.
if [[ "$INSTALL_MODE" == "dev" ]]; then
  COMPOSE_PROFILE="dev"
  BACKEND_SERVICE="backend-dev"
  WORKER_SERVICE="worker-dev"
else
  COMPOSE_PROFILE="prod"
  BACKEND_SERVICE="backend"
  WORKER_SERVICE="worker"
fi

log "Starting Docker ${COMPOSE_PROFILE} stack..."
run_with_retry 2 3 "${COMPOSE_CMD[@]}" --profile "$COMPOSE_PROFILE" up -d --build \
  || die "docker compose up failed"
wait_backend_health "$BACKEND_HOST_PORT"

if [[ "$DOMAIN" != "localhost" ]]; then
  ensure_nginx_port_available
  write_nginx_config "$DOMAIN" "$BACKEND_HOST_PORT" "$FRONTEND_HOST_PORT"
  SERVER_IP="$(resolve_server_ip)"
  wait_for_dns "$DOMAIN" "$SERVER_IP"
  request_tls "$DOMAIN" "$OWNER_EMAIL"
fi

log "Bootstrapping owner + workspace..."
BOOTSTRAP_JSON="$(
  "${COMPOSE_CMD[@]}" --profile "$COMPOSE_PROFILE" exec -T "$BACKEND_SERVICE" \
    python scripts/bootstrap_owner.py \
      --owner-name "$OWNER_NAME" \
      --owner-email "$OWNER_EMAIL"
)"
echo "$BOOTSTRAP_JSON"
WORKSPACE_ID="$(printf "%s" "$BOOTSTRAP_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["workspace_id"])')" || die "Failed to parse workspace_id from bootstrap output"
OWNER_USER_ID="$(printf "%s" "$BOOTSTRAP_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["owner_user_id"])')" || die "Failed to parse owner_user_id from bootstrap output"
[[ -n "$WORKSPACE_ID" ]] || die "Bootstrap did not return a workspace_id"
[[ -n "$OWNER_USER_ID" ]] || die "Bootstrap did not return an owner_user_id"

if [[ "$DOMAIN" == "localhost" ]]; then
  log "Enabling localhost auth bypass for owner user ${OWNER_USER_ID}..."
  AUTH_DEV_BYPASS_USER_ID="$OWNER_USER_ID"
  write_env_file .env
  verify_env_postconditions "$OWNER_USER_ID"
  "${COMPOSE_CMD[@]}" --profile "$COMPOSE_PROFILE" up -d --force-recreate \
    "$BACKEND_SERVICE" "$WORKER_SERVICE"
  wait_backend_health "$BACKEND_HOST_PORT"
  curl -fsS "http://127.0.0.1:${BACKEND_HOST_PORT}/api/v1/auth/me" >/dev/null \
    || die "Localhost auth bypass verification failed: /api/v1/auth/me returned non-200"
  curl -fsS "http://127.0.0.1:${BACKEND_HOST_PORT}/api/v1/workspaces" >/dev/null \
    || die "Localhost auth bypass verification failed: /api/v1/workspaces returned non-200"
fi

log "Importing default workflows (preselected: 2)..."
run_with_retry 3 5 "${COMPOSE_CMD[@]}" --profile "$COMPOSE_PROFILE" exec -T "$BACKEND_SERVICE" \
  python scripts/import_default_workflows.py \
    --workspace-id "$WORKSPACE_ID" \
    --workflow-id landing-page-builder \
    --workflow-id simple-writing \
  || warn "Default workflow import failed after retries — run manually: python scripts/import_default_workflows.py --workspace-id $WORKSPACE_ID --workflow-id landing-page-builder --workflow-id simple-writing"

echo
echo "Install complete (mode: ${COMPOSE_PROFILE})."
echo "Domain: $DOMAIN"
echo "Frontend URL: $FRONTEND_URL"
echo "Backend URL: $BACKEND_URL"
if [[ "$INSTALL_MODE" == "dev" ]]; then
  echo "Backend dev port: $BACKEND_DEV_HOST_PORT"
  echo "Frontend dev port (Vite HMR): $FRONTEND_DEV_HOST_PORT"
else
  echo "Backend host port: $BACKEND_HOST_PORT"
  echo "Frontend host port: $FRONTEND_HOST_PORT"
fi
echo "Workspace ID: $WORKSPACE_ID"
echo "Owner user ID: $OWNER_USER_ID"
echo "Owner email: $OWNER_EMAIL"
echo
echo "Next:"
echo "1) Open $FRONTEND_URL"
if [[ "$DOMAIN" == "localhost" ]]; then
  echo "2) Localhost auth bypass is enabled for owner ${OWNER_EMAIL}"
  echo "3) Open the app; it should auto-sign-in even after localStorage is cleared"
  if [[ "$INSTALL_MODE" == "dev" ]]; then
    echo ""
    echo "Hot-reload notes:"
    echo "  • Backend changes: edit files in backend/ — uvicorn auto-reloads"
    echo "  • Frontend changes: edit files in frontend/src/ — Vite HMR updates in-browser"
    echo "  • To restart services: docker compose --project-name $COMPOSE_PROJECT_NAME --profile dev restart backend-dev worker-dev"
    echo "  • To view logs: docker compose --project-name $COMPOSE_PROJECT_NAME --profile dev logs -f backend-dev"
  fi
else
  echo "2) Request magic link using owner email"
  echo "3) Login and verify imported workflows + handbook files"
fi
